Repository hevslc/JVM, pull requests merged in 2020-10, with the labels that each got.

#57 #45 e #46 - Correções para os warnings
  src/Opcode.cpp
Labels: Bug fix

#62 #58 - Uma primeira implementação para a classe Slot criada
  include/Slot.h
  src/Slot.cpp
Labels: enhancement

#65 fileName ok, redeclaration of 'LONG' fixed
  include/ClassFile.h
  include/Slot.h
  src/ClassFile.cpp
Labels: Bug fix, enhancement

#69 Flag #60
  include/Slot.h
  src/main.cpp
Labels: enhancement

#73 bug Floating Point fixed
  src/CpInfo.cpp
Labels: Bug fix
