Repository hevslc/JVM, pull requests merged in 2020-11, with the labels that each got.

#77 Frame interpreter #75 #74
  include/AttributeInfo.h
  include/ClassFile.h
  include/Frame.h
  include/Instructions.h
  include/Interpreter.h
  src/AttributeInfo.cpp
  src/Frame.cpp
  src/Instructions.cpp
  src/Interpreter.cpp
  src/main.cpp
Labels: enhancement

#79 Aprimorando a execução da JVM
  include/Frame.h
  include/Instructions.h
  src/Frame.cpp
  src/Instructions.cpp
  src/Interpreter.cpp
Labels: enhancement

#82 Criando execução para ldc2_w
  include/Frame.h
  include/Instructions.h
  include/Utils.h
  src/Frame.cpp
  src/Instructions.cpp
  src/Interpreter.cpp
  src/Utils.cpp
Labels: enhancement

#85 #84 - Fazendo a inicialização do vetor de variáveis locais
  include/AttributeInfo.h
  include/Variables.h
  src/AttributeInfo.cpp
  src/Frame.cpp
Labels: enhancement

#88 instrucoes iconst_<i>
  src/Instructions.cpp
Labels: enhancement

#89 87 arrays instructions
  include/Definitions.h
  include/Instructions.h
  src/Instructions.cpp
Labels: enhancement

#91 #90 - Correção do bug
  src/Instructions.cpp
Labels: Bug fix

#96 correcao e aprimoramento multianewarray instr
  include/Definitions.h
  src/Instructions.cpp
Labels: Bug fix, enhancement

#100 get high and low double
  include/Slot.h
  src/Interpreter.cpp
  src/Slot.cpp
Labels: enhancement

#101 get high low long
  include/Slot.h
  src/Slot.cpp
Labels: enhancement

#108 87 arrays instructions
  include/AttributeInfo.h
  include/Definitions.h
  include/Instructions.h
  include/OperandStack.h
  include/Variables.h
  src/AttributeInfo.cpp
  src/Frame.cpp
  src/Instructions.cpp
  src/OperandStack.cpp
  src/Variables.cpp
Labels: Bug fix, enhancement, refactoring

#109 Funções Store
  src/Instructions.cpp
Labels: enhancement

#110 Criação da instrução ldc
  examples/float_logico.class
  include/OperandStack.h
  include/Slot.h
  include/Utils.h
  src/Instructions.cpp
  src/OperandStack.cpp
  src/Utils.cpp
Labels: enhancement

#116 Auxiliares adicionar/push de u8 em Variables/Operands
  include/OperandStack.h
  include/Variables.h
  src/Instructions.cpp
  src/OperandStack.cpp
  src/Utils.cpp
  src/Variables.cpp
Labels: enhancement

#119 #118 - Atualização do Slot
  include/Slot.h
  src/Instructions.cpp
  src/OperandStack.cpp
Labels: enhancement, refactoring

#124 pop e pop2
  src/Instructions.cpp
Labels: enhancement

#125 117 invoker getstatic
  include/Instructions.h
  include/Utils.h
  src/Instructions.cpp
  src/Utils.cpp
Labels: enhancement

#130 Instruções fcmp<op> e dcmp<op>
  examples/double_logico.class
  src/Instructions.cpp
Labels: enhancement

#138 pop e pop2
  src/Instructions.cpp
Labels: enhancement

#132 Instruções if<conf>
  include/Instructions.h
  include/Utils.h
  src/Instructions.cpp
  src/Utils.cpp
Labels: enhancement

#134 126-ladd-iinc-goto-return
  examples/testesLadeira/double_aritmetica.class
  examples/testesLadeira/multi-nome.class
  examples/testesLadeira/tableswitch.class
  include/Utils.h
  src/Instructions.cpp
Labels: enhancement

#137 Wide
  include/Instructions.h
  src/Instructions.cpp
Labels: enhancement

#139 Instruções d2l d2i d2f
  examples/double_cast.class
  src/Instructions.cpp
Labels: enhancement

#145 astores
  include/OperandStack.h
  src/Instructions.cpp
  src/OperandStack.cpp
Labels: enhancement

#147 swap add
  src/Instructions.cpp
Labels: enhancement

#146 Criação das instruções _sipush _i2l _i2f _i2d _i2b _i2c _i2s
  examples/testesLadeira/int_cast.class
  include/OperandStack.h
  include/Slot.h
  include/Utils.h
  src/Instructions.cpp
  src/OperandStack.cpp
  src/Utils.cpp
Labels: enhancement

#142 Instruções f2d, f2i e f2l
  examples/testesLadeira/double_cast.class
  examples/testesLadeira/double_logico.class
  examples/testesLadeira/float_cast.class
  examples/testesLadeira/float_logico.class
  src/Instructions.cpp
Labels: enhancement

#128 instrucoes dup implementadas
  examples/Belote.class
  src/Instructions.cpp
Labels: enhancement

#148 121 d/i/l/f sub(), add(), mul(), div(), neg(), rem()
  examples/Object.class
  examples/float_aritmetica.class
  examples/int_aritmetica.class
  examples/long_aritmetica.class
  examples/multi-nome.class
  examples/tableswitch.class
  include/OperandStack.h
  src/Instructions.cpp
  src/OperandStack.cpp
Labels: enhancement

#151 l2i, l2d e l2f add
  src/Instructions.cpp
Labels: enhancement

#153 lcmp add
  src/Instructions.cpp
Labels: enhancement

#158 i/l/iu/lushr add
  src/Instructions.cpp
Labels: enhancement

#150 int e long logic op
  examples/int_logico.class
  src/Instructions.cpp
Labels: enhancement

#160 Lookupswitch.implementation
  examples/LookupSwitch.class
  src/Instructions.cpp
  src/Opcode.cpp
Labels: enhancement

#162 140 aload aload i test multi.class
  include/Definitions.h
  include/Instructions.h
  include/Utils.h
  src/Instructions.cpp
  src/Utils.cpp
Labels: enhancement

#165 164 double float int long short
  src/Instructions.cpp
  src/Utils.cpp
Labels: Bug fix, enhancement

#167 correcao/add instr para int_logico e vetor .class
  src/Instructions.cpp
Labels: Bug fix, enhancement

#178 Criação do ldc_w
  src/Instructions.cpp
Labels: enhancement
